"""empty message

Revision ID: 01f44acc7779
Revises: bb13d41a4bc5
Create Date: 2019-02-16 19:12:14.913487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f44acc7779'
down_revision = 'bb13d41a4bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('type', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'type')
    # ### end Alembic commands ###
