"""empty message

Revision ID: 0a638e9039a3
Revises: 5a3c1959f4c7
Create Date: 2019-02-25 17:46:31.863714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a638e9039a3'
down_revision = '5a3c1959f4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'goal',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'goal',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
