"""empty message

Revision ID: 45552dbca382
Revises: a91d9cc0a07a
Create Date: 2019-01-25 01:54:55.106242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45552dbca382'
down_revision = 'a91d9cc0a07a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'second_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('second_image', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
