"""empty message

Revision ID: a91d9cc0a07a
Revises: edce5fbeb7f4
Create Date: 2019-01-25 01:52:18.175381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91d9cc0a07a'
down_revision = 'edce5fbeb7f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'product', ['id'])
    op.add_column('user', sa.Column('email', sa.String(length=128), nullable=False))
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['login'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email')
    op.drop_constraint(None, 'product', type_='unique')
    # ### end Alembic commands ###
