"""empty message

Revision ID: bc4d00d5ab83
Revises: fd86560bf4ff
Create Date: 2019-02-17 16:18:40.066807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4d00d5ab83'
down_revision = 'fd86560bf4ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('id_color', sa.Integer(), nullable=True))
    op.drop_constraint('items_color_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'color', ['id_color'], ['id'])
    op.drop_column('items', 'color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('color', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_color_fkey', 'items', 'color', ['color'], ['id'])
    op.drop_column('items', 'id_color')
    # ### end Alembic commands ###
