"""empty message

Revision ID: cd827a996df8
Revises: 45552dbca382
Create Date: 2019-01-25 01:55:14.897993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd827a996df8'
down_revision = '45552dbca382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('second_image', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'second_image')
    # ### end Alembic commands ###
