"""empty message

Revision ID: fd86560bf4ff
Revises: 011026aef993
Create Date: 2019-02-16 22:04:10.397334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd86560bf4ff'
down_revision = '011026aef993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('color', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'color', ['color'], ['id'])
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('goal', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'goal')
    op.drop_column('product', 'category_id')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'color')
    # ### end Alembic commands ###
